png("plot3.png", width=480, height=480)
with(febpower, plot(Sub_metering_1 ~ DateTime, type="l", xlab= "", ylab="Energy Sub Metering"))
lines(febpower$Sub_metering_2 ~ febpower$DateTime, col = 'Red')
lines(febpower$Sub_metering_3 ~ febpower$DateTime, col = 'Blue')
legend("topright", lty=1, lwd =3, col=c("black","red","blue") ,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()